apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-important-roza
  namespace: roza-final
  labels:
    id: ds-important
    uuid: 18426a0b-5f59-4e10-923f-c0e078e82462
spec:
  selector:
    matchLabels:
      id: ds-important
      uuid: 18426a0b-5f59-4e10-923f-c0e078e82462
  template:
    metadata:
      labels:
        id: ds-important
        uuid: 18426a0b-5f59-4e10-923f-c0e078e82462
    spec:
      nodeSelector: 
        # role: worker
        {}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: deployment
        image: httpd:2.4-alpine
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi


