apiVersion: v1
kind: Pod
metadata:
  name: ready-if-service-ready
  namespace: roza-final
spec:
  containers:
  - name: nginx
    image: nginx:1.16.1-alpine
    livenessProbe:
      exec:
        command: ["true"]
      initialDelaySeconds: 1
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 2
      successThreshold: 1
    readinessProbe:
      exec:
        command:
        - wget
        - -T2
        - -O-
        - http://service-am-i-ready:80
      initialDelaySeconds: 1
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 2
