apiVersion: v1
kind: Pod
metadata:
  name: am-i-ready
  namespace: roza-final
  labels:
    app: cross-server-ready
spec:
  containers:
  - name: nginx
    image: nginx:1.16.1-alpine

---

apiVersion: v1
kind: Service
metadata:
  name: service-am-i-ready
  namespace: roza-final
spec:
  selector:
    app: cross-server-ready
  ports:
  - name: http
    port: 80
    targetPort: 80