apiVersion: v1
kind: PersistentVolume
metadata:
  name: safari-pv-roza
  namespace: roza-final
spec:
  capacity:
    storage: 1Gi
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/volumes/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: safari-pvc-roza
  namespace: roza-final
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: safari
  namespace: roza-final
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: httpd:2.4.41-alpine
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/tmp/safari-data"
          name: roza-pd
      volumes:
        - name: roza-pd
          persistentVolumeClaim:
            claimName: safari-pvc-roza 
