apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: roza-secret
spec:
  containers:
  - name: busybox
    image: busybox:1.31.1
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    env:
    - name: APP_USER
      valueFrom:
        secretKeyRef:
          name: secret2
          key: user
    - name: APP_PASS
      valueFrom:
        secretKeyRef:
          name: secret2
          key: pass
    volumeMounts:
    - name: secret1-mount
      mountPath: "/tmp/secret1"
      readOnly: true
  volumes:
  - name: secret1-mount
    secret:
      secretName: secret1