apiVersion: v1
kind: Pod
metadata:
  name: multi-container-playground-roza
  namespace: default
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}
  containers:
  - name: c1
    image: nginx:1.17.6-alpine
    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
  - name: c2
    image: busybox:1.31.1
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
    command: [ "/bin/sh", "-c", "while true; do date >> /shared/date.log; sleep 1; done" ]
  - name: c3
    image: busybox:1.31.1
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
    command: [ "/bin/sh", "-c", "tail -f /shared/date.log" ]

